// Technology stack detector. Fingerprints a target from a raw HTTP response
// (headers + body + cookies). Pure, no network. Reuses parseResponse.
import { parseResponse } from './httpanalyzer.js';

// Rule shape: { cat, name, header?:[name,re], hAny?:re, cookie?:re, body?:re,
//   url?:re, ver?:{ src:'header'|'body'|'hAny', header?, re } }
const R = [
  // ---- Server ----
  { cat: 'server', name: 'Nginx', header: ['server', /nginx/i], ver: { src: 'header', header: 'server', re: /nginx\/([\d.]+)/i } },
  { cat: 'server', name: 'Apache', header: ['server', /apache/i], ver: { src: 'header', header: 'server', re: /apache\/([\d.]+)/i } },
  { cat: 'server', name: 'Microsoft IIS', header: ['server', /iis|microsoft-httpapi/i], ver: { src: 'header', header: 'server', re: /iis\/([\d.]+)/i } },
  { cat: 'server', name: 'OpenResty', header: ['server', /openresty/i], ver: { src: 'header', header: 'server', re: /openresty\/([\d.]+)/i } },
  { cat: 'server', name: 'LiteSpeed', header: ['server', /litespeed/i] },
  { cat: 'server', name: 'Caddy', header: ['server', /caddy/i] },
  { cat: 'server', name: 'Apache Tomcat', hAny: /coyote|tomcat/i },
  { cat: 'server', name: 'Jetty', header: ['server', /jetty/i] },
  { cat: 'server', name: 'Gunicorn', header: ['server', /gunicorn/i] },
  { cat: 'server', name: 'Werkzeug (Flask dev)', header: ['server', /werkzeug/i] },
  { cat: 'server', name: 'Kestrel (.NET)', header: ['server', /kestrel/i] },
  { cat: 'server', name: 'Cowboy (Erlang)', header: ['server', /cowboy/i] },

  // ---- CDN ----
  { cat: 'cdn', name: 'Cloudflare', hAny: /cf-ray|cf-cache-status|^server:\s*cloudflare/im },
  { cat: 'cdn', name: 'Fastly', hAny: /x-served-by:.*cache|x-fastly|fastly/i },
  { cat: 'cdn', name: 'Akamai', hAny: /x-akamai|akamai|x-cache-key/i },
  { cat: 'cdn', name: 'Amazon CloudFront', hAny: /x-amz-cf-id|via:.*cloudfront/i },
  { cat: 'cdn', name: 'Vercel', hAny: /x-vercel-id|server:\s*vercel/i },
  { cat: 'cdn', name: 'Netlify', hAny: /x-nf-request-id|server:\s*netlify/i },
  { cat: 'cdn', name: 'Sucuri', hAny: /x-sucuri-id|x-sucuri-cache/i },
  { cat: 'cdn', name: 'KeyCDN', hAny: /x-edge-location|keycdn/i },
  { cat: 'cdn', name: 'Azure CDN', hAny: /x-azure-ref|x-msedge-ref/i },
  { cat: 'cdn', name: 'BunnyCDN', hAny: /bunnycdn|server:\s*bunnycdn/i },

  // ---- WAF ----
  { cat: 'waf', name: 'Cloudflare WAF', hAny: /cf-ray/i },
  { cat: 'waf', name: 'Akamai (Kona)', hAny: /akamaighost|x-akamai-transformed/i },
  { cat: 'waf', name: 'Imperva / Incapsula', cookie: /incap_ses|visid_incap/i },
  { cat: 'waf', name: 'Imperva / Incapsula', hAny: /x-iinfo|x-cdn:\s*incapsula/i },
  { cat: 'waf', name: 'Sucuri WAF', hAny: /x-sucuri/i },
  { cat: 'waf', name: 'AWS WAF', hAny: /awselb|x-amzn-waf/i },
  { cat: 'waf', name: 'F5 BIG-IP ASM', cookie: /^.*BIGipServer|TS[0-9a-f]{6,}/i },
  { cat: 'waf', name: 'Barracuda', cookie: /barra_counter_session/i },
  { cat: 'waf', name: 'ModSecurity', body: /Mod_Security|This error was generated by Mod_Security|Not Acceptable!/i },
  { cat: 'waf', name: 'Wordfence', body: /Generated by Wordfence|wordfence/i },
  { cat: 'waf', name: 'DenyAll', cookie: /sessioncookie|datadome/i },
  { cat: 'waf', name: 'DataDome', cookie: /datadome/i },

  // ---- Frontend frameworks ----
  { cat: 'frontend', name: 'Next.js', body: /__NEXT_DATA__|\/_next\//i, ver: { src: 'body', re: /"buildId":"([\w-]+)"/ } },
  { cat: 'frontend', name: 'Nuxt.js', body: /__NUXT__|\/_nuxt\//i },
  { cat: 'frontend', name: 'React', body: /data-reactroot|react(?:-dom)?(?:\.production)?(?:\.min)?\.js|__REACT_DEVTOOLS/i },
  { cat: 'frontend', name: 'Vue.js', body: /data-v-[0-9a-f]{8}|vue(?:\.min)?\.js|__VUE__/i },
  { cat: 'frontend', name: 'Angular', body: /ng-version=|angular(?:\.min)?\.js|\bng-app\b/i, ver: { src: 'body', re: /ng-version="([\d.]+)"/ } },
  { cat: 'frontend', name: 'Svelte / SvelteKit', body: /svelte|__sveltekit/i },
  { cat: 'frontend', name: 'Gatsby', body: /___gatsby|\/page-data\//i },
  { cat: 'frontend', name: 'Ember.js', body: /ember(?:\.min)?\.js|data-ember/i },
  { cat: 'frontend', name: 'Alpine.js', body: /alpine(?:\.min)?\.js|x-data=/i },
  { cat: 'frontend', name: 'jQuery', body: /jquery[.-][\d.]+(?:\.min)?\.js|jquery(?:\.min)?\.js/i, ver: { src: 'body', re: /jquery[.-](\d+(?:\.\d+)+)/i } },
  { cat: 'frontend', name: 'Bootstrap', body: /bootstrap[.-][\d.]+|bootstrap(?:\.min)?\.(?:css|js)/i, ver: { src: 'body', re: /bootstrap[.-](\d+(?:\.\d+)+)/i } },
  { cat: 'frontend', name: 'Tailwind CSS', body: /tailwind|--tw-/i },

  // ---- Backend / language ----
  { cat: 'backend', name: 'Node.js / Express', header: ['x-powered-by', /express/i] },
  { cat: 'backend', name: 'PHP', header: ['x-powered-by', /php/i], ver: { src: 'header', header: 'x-powered-by', re: /php\/([\d.]+)/i } },
  { cat: 'backend', name: 'PHP', cookie: /PHPSESSID/i },
  { cat: 'backend', name: 'ASP.NET', hAny: /x-aspnet-version|x-aspnetmvc-version/i, ver: { src: 'hAny', re: /x-aspnet-version:\s*([\d.]+)/i } },
  { cat: 'backend', name: 'ASP.NET', cookie: /ASP\.NET_SessionId/i },
  { cat: 'backend', name: 'Java (Servlet)', cookie: /JSESSIONID/i },
  { cat: 'backend', name: 'Ruby on Rails', cookie: /_session_id|_rails/i },
  { cat: 'backend', name: 'Ruby (Phusion Passenger)', hAny: /phusion passenger|x-powered-by:.*phusion/i },
  { cat: 'backend', name: 'Django (Python)', cookie: /csrftoken|django/i },
  { cat: 'backend', name: 'Laravel (PHP)', cookie: /laravel_session|XSRF-TOKEN/i },
  { cat: 'backend', name: 'Spring (Java)', hAny: /x-application-context/i },
  { cat: 'backend', name: 'ColdFusion', cookie: /CFID|CFTOKEN/i },
  { cat: 'backend', name: 'Flask (Python)', header: ['server', /werkzeug/i] },

  // ---- CMS ----
  { cat: 'cms', name: 'WordPress', body: /\/wp-content\/|\/wp-includes\/|wp-json|name="generator" content="WordPress/i, ver: { src: 'body', re: /WordPress ([\d.]+)/i } },
  { cat: 'cms', name: 'WordPress', hAny: /x-pingback/i },
  { cat: 'cms', name: 'Drupal', hAny: /x-generator:\s*drupal|x-drupal-cache/i, ver: { src: 'hAny', re: /drupal ([\d.]+)/i } },
  { cat: 'cms', name: 'Drupal', body: /\/sites\/default\/files|drupal\.js/i },
  { cat: 'cms', name: 'Joomla', body: /\/media\/jui\/|name="generator" content="Joomla/i },
  { cat: 'cms', name: 'Magento', body: /\/skin\/frontend\/|Mage\.Cookies|\/static\/version\d/i },
  { cat: 'cms', name: 'Shopify', hAny: /x-shopify|x-sorting-hat/i },
  { cat: 'cms', name: 'Shopify', body: /cdn\.shopify\.com|Shopify\.theme/i },
  { cat: 'cms', name: 'Wix', hAny: /x-wix-request-id/i },
  { cat: 'cms', name: 'Squarespace', body: /squarespace|static1\.squarespace/i },
  { cat: 'cms', name: 'Ghost', body: /name="generator" content="Ghost/i },
  { cat: 'cms', name: 'Webflow', body: /webflow|data-wf-page/i },
  { cat: 'cms', name: 'Adobe Experience Manager', body: /\/etc\.clientlibs\/|\/content\/dam\//i },
  { cat: 'cms', name: 'Sitecore', cookie: /SC_ANALYTICS_GLOBAL_COOKIE/i },

  // ---- Cloud / hosting ----
  { cat: 'cloud', name: 'AWS (S3)', body: /[a-z0-9.-]+\.s3[.-][a-z0-9-]*\.amazonaws\.com|s3\.amazonaws\.com/i },
  { cat: 'cloud', name: 'AWS', hAny: /x-amz-|x-amzn-/i },
  { cat: 'cloud', name: 'Google Cloud / Firebase', body: /storage\.googleapis\.com|firebaseio\.com|firebaseapp\.com|appspot\.com/i },
  { cat: 'cloud', name: 'Microsoft Azure', body: /azurewebsites\.net|blob\.core\.windows\.net/i },
  { cat: 'cloud', name: 'Heroku', hAny: /via:.*vegur|server:\s*cowboy/i },
  { cat: 'cloud', name: 'DigitalOcean Spaces', body: /digitaloceanspaces\.com/i },
  { cat: 'cloud', name: 'Vercel', hAny: /x-vercel-id/i },
  { cat: 'cloud', name: 'Netlify', hAny: /x-nf-request-id/i },

  // ---- Analytics / third-party ----
  { cat: 'analytics', name: 'Google Analytics', body: /google-analytics\.com|gtag\(|ga\.js|googletagmanager\.com\/gtag/i },
  { cat: 'analytics', name: 'Google Tag Manager', body: /googletagmanager\.com\/gtm/i },
  { cat: 'analytics', name: 'Segment', body: /cdn\.segment\.com|analytics\.track/i },
  { cat: 'analytics', name: 'Mixpanel', body: /cdn\.mxpnl\.com|mixpanel/i },
  { cat: 'analytics', name: 'Hotjar', body: /static\.hotjar\.com|hotjar/i },
  { cat: 'analytics', name: 'Sentry', body: /sentry-cdn|@sentry|browser\.sentry/i },
  { cat: 'analytics', name: 'Intercom', body: /widget\.intercom\.io|intercomSettings/i },
  { cat: 'analytics', name: 'Stripe', body: /js\.stripe\.com/i },
  { cat: 'analytics', name: 'reCAPTCHA', body: /google\.com\/recaptcha|grecaptcha/i },
  { cat: 'analytics', name: 'Datadog RUM', body: /datadog|dd-rum/i },

  // ---- Database (guessed from errors / drivers) ----
  { cat: 'database', name: 'MongoDB (guessed)', body: /MongoError|mongoose|mongodb:\/\//i },
  { cat: 'database', name: 'MySQL (guessed)', body: /SQL syntax.*MySQL|mysqli?_|mysql_fetch/i },
  { cat: 'database', name: 'PostgreSQL (guessed)', body: /PG::|PostgreSQL|psql:|pg_query/i },
  { cat: 'database', name: 'Microsoft SQL Server (guessed)', body: /SQLSTATE|System\.Data\.SqlClient|Microsoft SQL Server/i },
  { cat: 'database', name: 'Oracle (guessed)', body: /ORA-\d{5}/i },
  { cat: 'database', name: 'SQLite (guessed)', body: /SQLite3?::|sqlite_/i },
  { cat: 'database', name: 'Redis (guessed)', body: /redis:\/\/|RedisError/i },
  { cat: 'database', name: 'Elasticsearch (guessed)', body: /"_shards"|elasticsearch/i },
];

export const STACK_CATEGORIES = ['frontend', 'backend', 'database', 'cms', 'server', 'cdn', 'waf', 'cloud', 'analytics'];

function ctxFromParsed(p, extraBody = '') {
  const headerLines = Object.entries(p.headers || {}).map(([k, v]) => `${k}: ${v}`).join('\n');
  const cookieStr = [...(p.setCookies || []), p.headers?.cookie || ''].join('; ');
  return {
    get: (n) => (p.headers || {})[n] || '',
    headerLines,
    cookieStr,
    body: (p.body || '') + '\n' + extraBody,
  };
}

function matchRule(r, ctx) {
  if (r.header && !r.header[1].test(ctx.get(r.header[0]))) return false;
  if (r.hAny && !r.hAny.test(ctx.headerLines)) return false;
  if (r.cookie && !r.cookie.test(ctx.cookieStr)) return false;
  if (r.body && !r.body.test(ctx.body)) return false;
  // must have matched at least one provided matcher
  return !!(r.header || r.hAny || r.cookie || r.body);
}
function versionOf(r, ctx) {
  if (!r.ver) return '';
  const hay = r.ver.src === 'header' ? ctx.get(r.ver.header) : r.ver.src === 'hAny' ? ctx.headerLines : ctx.body;
  const m = (hay || '').match(r.ver.re);
  return m ? m[1] : '';
}

// detect from a parsed response context. Returns deduped detections.
export function detectStack(ctx) {
  const out = [];
  const seen = new Set();
  for (const r of R) {
    if (!matchRule(r, ctx)) continue;
    const key = `${r.cat}|${r.name}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ cat: r.cat, name: r.name, version: versionOf(r, ctx) });
  }
  return out;
}

export function detectFromResponse(raw, extraBody = '') {
  return detectStack(ctxFromParsed(parseResponse(raw), extraBody));
}

// Build a context from a stored subdomain httpx record (limited: server/title/tech).
export function detectFromRecord(rec, extraBody = '') {
  const headers = {};
  if (rec.server) headers.server = rec.server;
  const body = `${(rec.tech || []).join(' ')} ${rec.title || ''} ${extraBody}`;
  return detectStack(ctxFromParsed({ headers, setCookies: [], body }, ''));
}
